---
# chocomilk vars

# Package Changelog
changelog: 'https://raw.githubusercontent.com/open-circle-ltd/chocolatey.version/master/lenovo-system-update.json'

# Regex for Version
version: "{{ register_changelog.content |
  regex_search('([0-9]+.[0-9]+.[0-9]+.[0-9])')
  }}"

# Download URL
url: 'https://download.lenovo.com/pccbbs/thinkvantage_en/system_update_{{ version }}.exe'

searchreplace:
  'tools/chocolateyinstall.ps1':
    - regwxp: (^\s*[$]*urlPackage\s*=\s*)('.*')
      replace: "$urlPackage = '{{ url }}'"
    - regwxp: (^\s*[$]*checksumPackage\s*=\s*)('.*')
      replace: "$checksumPackage = '{{ file_hash }}'"

# readme to description
readme:
  start: 5
  end: 41

# deploy
deploy:
# not public
#  - provider: chocolatey
#    repository: "https://push.chocolatey.org/"
#    key: "{{ lookup('env','CHOCOLATEY_ORG_API_KEY') }}"
  - provider: chocolatey
    repository: "https://nuget.itigo.tech/upload"
    key: "{{ lookup('env','CHOCOLATEY_ITIGO_API_KEY') }}"
  - provider: github
    name: "OpenCircle-Choco-Bot"
    email: "chocomilk@open-circle.ch"
    url: github.com/open-circle-ltd/chocolatey.lenovo-system-update.git
    key: "{{ lookup('env','GITHUB_API_KEY') }}"

# Notification
notifications:
  - provider: mattermost
    url: "https://chat.open-circle.ch"
    key: "{{ lookup('env','MATTERMOST_API_KEY') }}"
    channel: "notification-chocolatey"
